language: ruby
rvm:
- 2.3.1
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database test_app_uniqsystems;' -U postgres
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:migrate RAILS_ENV=test
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start